//! Mobile FFI scaffold for Stratum (Phase 8).
//!
//! This crate is the *thin* C-ABI / language-binding surface that ships
//! inside the iOS Swift Package and the Android AAR. It deliberately
//! contains no business logic — the actual runtime lives in
//! `stratum-runtime`, which this crate will re-export across the FFI
//! boundary as Phase 8 fills in.
//!
//! ## Why a separate crate?
//!
//! * `stratum-runtime` is `cdylib`-hostile (its dep graph pulls in
//!   `ring`/`rustls` which won't cross-compile to `aarch64-apple-ios`
//!   without an Xcode toolchain; see `docs/phase-8-readiness.md`). We
//!   want a *minimal* C ABI that can be produced even on a bare host.
//! * The C header generated by `cbindgen` and the Swift package that
//!   consumes it should both be derived from a small, intentional
//!   surface — not from the whole runtime.
//!
//! See `docs/phase-8-ios-build.md` for the iOS build flow.

// The crate ships a single `extern "C"` shim under `cfg(not(test))`; the
// workspace lint set bans `unsafe_code` at the `deny` level (not
// `forbid`), so the per-call `#[allow(unsafe_code, reason = …)]` on that
// shim is what overrides it. We do not redeclare `forbid(unsafe_code)`
// here for that reason — see `ffi::stratum_mobile_version`.
#![warn(missing_docs)]

/// Mobile-core FFI surface, in safe Rust.
///
/// Functions in this module are re-exported via `pub use` from the crate
/// root with `#[unsafe(no_mangle)]` + `extern "C"` shims under a
/// `cfg(not(test))` gate, so that the workspace's `unsafe_code = "deny"`
/// stays honest for `cargo test`.
pub mod api {
    /// Semantic version of the mobile-core crate. Mirrors
    /// `CARGO_PKG_VERSION` and is what `StratumMobile.version` returns
    /// on the Swift side.
    #[must_use]
    pub const fn version() -> &'static str {
        // The trailing NUL lets the C-ABI shim hand the pointer straight
        // to Swift's `String(cString:)` without an extra allocation.
        concat!(env!("CARGO_PKG_VERSION"), "\0")
    }
}

// --- C ABI shims --------------------------------------------------------
//
// These are the only `unsafe` / `no_mangle` items in the crate, and they
// are intentionally tiny: each is a one-line forwarder to `api::*`. They
// are compiled only for non-test, non-doctest builds so the workspace's
// `unsafe_code = "deny"` rule still fires on regular `cargo test`.
//
// The `cdylib` / `staticlib` crate-types only matter for the platform
// builds (`--target aarch64-apple-ios`, `--target aarch64-linux-android`,
// …) where we deliberately allow the shim.

#[cfg(not(test))]
mod ffi {
    use core::ffi::c_char;

    /// Returns a pointer to a NUL-terminated, static C string with the
    /// crate's semantic version. The returned pointer is valid for the
    /// lifetime of the process and must not be freed by the caller.
    ///
    /// # Safety
    ///
    /// The pointer is to a `'static` string baked into the binary; it is
    /// always non-null and always NUL-terminated. Callers must not write
    /// through it.
    #[allow(
        unsafe_code,
        reason = "FFI entry point; the body is a single pointer cast over a 'static NUL-terminated string."
    )]
    #[allow(
        unreachable_pub,
        reason = "Exported via #[no_mangle] for the C ABI; Rust visibility is not how this symbol is reached."
    )]
    #[unsafe(no_mangle)]
    pub const extern "C" fn stratum_mobile_version() -> *const c_char {
        super::api::version().as_ptr().cast::<c_char>()
    }
}

#[cfg(test)]
mod tests {
    use super::api;

    #[test]
    fn version_matches_cargo_pkg_version_with_nul() {
        let v = api::version();
        assert!(
            v.ends_with('\0'),
            "version() must be NUL-terminated for the C ABI"
        );
        assert_eq!(&v[..v.len() - 1], env!("CARGO_PKG_VERSION"));
    }
}
