#ifndef STRATUM_MOBILE_H
#define STRATUM_MOBILE_H

#pragma once

/* Generated by cbindgen — do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Returns a pointer to a NUL-terminated, static C string with the
 * crate's semantic version. The returned pointer is valid for the
 * lifetime of the process and must not be freed by the caller.
 */
const char *stratum_mobile_version(void);

#endif /* STRATUM_MOBILE_H */
